server:
  port: 8189
  servlet:
    context-path: /api
spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  security:
    user:
      name: admin
      password: admin